training_params:
    input_dim: 512
    output_dim: 512
model_params:  
    num_latents: 64
    latent_dim: 32
    cross_heads: 1
    latent_heads: 8
    cross_dim_head: 64
    latent_dim_head: 64
    attn_dropout: 0.
    ff_dropout: 0.1
    weight_tie_layers: True
    self_per_cross_attn: 6
    depth: 8